version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ds:
        patterns:
          - "@navikt/ds-*"
      dekorator:
        patterns:
          - "@navikt/nav-dekoratoren-moduler"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      test:
        patterns:
          - "@testing-library/*"
      styledcomponents:
        patterns:
          - "styled-components"
          - "@types/styled-components"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-babel-macros"
          - "vitest"
          - "@vitejs/*"