apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-avtaler-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://digisos.dev.nav.no/sosialhjelp/avtaler
  liveness:
    path: /sosialhjelp/avtaler/internal/isalive
  readiness:
    path: /sosialhjelp/avtaler/internal/isready
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler/internal/metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  secureLogs:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
  tokenx:
    enabled: true
  env:
    - name: AVTALER_API_BASE_URL
      value: 'http://sosialhjelp-avtaler-api-dev.teamdigisos.svc.cluster.local'
    - name: AVTALER_API_TARGET_AUDIENCE
      value: dev-gcp:teamdigisos:sosialhjelp-avtaler-api-dev
    - name: PORT
      value: '5000'
    - name: MILJO
      value: 'dev-gcp'

  accessPolicy:
    outbound:
      external:
        - host: "oidc-ver2.difi.no"
      rules:
        - application: sosialhjelp-avtaler-api-dev
