apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-avtaler
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://sosialhjelp-avtaler-mock.dev.nav.no/sosialhjelp/avtaler
  liveness:
    path: /sosialhjelp/avtaler/internal/isAlive
  readiness:
    path: /sosialhjelp/avtaler/internal/isready
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler/internal/metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  secureLogs:
    enabled: true
  env:
    - name: AVTALER_API_BASE_URL
      value: ''
    - name: AVTALER_API_TARGET_AUDIENCE
      value: ''
    - name: PORT
      value: '5000'
    - name: USE_MSW
      value: 'true'
    - name: GIT_COMMIT
      value: {{commit}}