apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-avtaler
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://www.nav.no/sosialhjelp/avtaler
  liveness:
    path: /sosialhjelp/avtaler/internal/isalive
  readiness:
    path: /sosialhjelp/avtaler/internal/isready
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler/internal/metrics
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 61Mi
  secureLogs:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
  tokenx:
    enabled: true
  env:
    - name: AVTALER_API_BASE_URL
      value: 'http://sosialhjelp-avtaler-api.teamdigisos.svc.cluster.local'
    - name: AVTALER_API_TARGET_AUDIENCE
      value: prod-gcp:teamdigisos:sosialhjelp-avtaler-api
    - name: PORT
      value: '5000'
    - name: MILJO
      value: 'prod-gcp'
  accessPolicy:
    outbound:
      rules:
        - application: sosialhjelp-avtaler-api
