apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-avtaler
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - "https://www.nav.no/sosialhjelp/avtaler"
  liveness:
    path: /sosialhjelp/avtaler/internal/isalive
  readiness:
    path: /sosialhjelp/avtaler/internal/isready
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler/internal/metrics
  replicas:
    min: 2
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
  tokenx:
    enabled: true
  env:
    - name: AVTALER_API_BASE_URL
      value: "http://sosialhjelp-avtaler-api.teamdigisos.svc.cluster.local"
    - name: AVTALER_API_TARGET_AUDIENCE
      value: "prod-gcp:teamdigisos:sosialhjelp-avtaler-api"
    - name: PORT
      value: "5000"
    - name: MILJO
      value: "prod-gcp"
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
      rules:
        - application: sosialhjelp-avtaler-api
        - application: nav-dekoratoren
          namespace: personbruker
