apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{applicationName}}
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 5000
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  liveness:
    path: /sosialhjelp/avtaler/internal/isalive
  readiness:
    path: /sosialhjelp/avtaler/internal/isready
  prometheus:
    enabled: true
    path: /sosialhjelp/avtaler/internal/metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  secureLogs:
    enabled: true
{{#if idportenEnabled}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
{{/if}}
  tokenx:
    enabled: {{tokenXEnabled}}
  env:
  {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
  {{/each}}
  accessPolicy:
    outbound:
      rules:
      {{#each outboundRulesApplications}}
          - application: "{{this}}"
      {{/each}}
