name: "Deploy to Production (prod-gcp)"

on:
  workflow_run:
    workflows: ["Build code and run tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    name: "Build Image"
    uses: ./.github/workflows/build_image.yml
    secrets: inherit

  deploy-image:
    name: "Deploy image to prod"
    needs: build-image
    uses: ./.github/workflows/deploy_image.yml
    secrets: inherit
    with:
      environment: "prod"
      image: ${{ needs.build-image.outputs.image }}
