name: "Deploy to Development (dev-gcp)"
run-name: Deploy '${{ github.ref_name }}' to '${{ github.event.inputs.config-file-name }}'

on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: "Config-fil som skal deployes"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "mock"

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    name: "Build Image"
    uses: ./.github/workflows/build_image.yml
    secrets: inherit

  deploy-image:
    name: "Deploy image to ${{ inputs.config-file-name }}"
    needs: build-image
    uses: ./.github/workflows/deploy_image.yml
    secrets: inherit
    with:
      environment: ${{ inputs.config-file-name }}
      image: ${{ needs.build-image.outputs.image }}
